[pytest]
markers =
    smoke: basic validation tests
    suspend: auto suspend tests
    resume: auto resume tests
    negative: negative test cases
    state: state transition tests

addopts = -v --html=reports/test_report.html --self-contained-html